### ISSUE TITLE
Empty space above search box

### ISSUE THREAD

**Issue by AnInfiniteNumberofMonkeys** [re-co/recoda-ws#18]
<img width="400" alt="Context" src="https://user-images.githubusercontent.com/13838253/124369009-20a7e080-dc1c-11eb-8620-182d5a051221.png">

**Comment by re-co** [comment]
Please disable Editor Enhancer! 
We are not testing plugin with other 3rd party plugins, we need resolve issues between oxygen and this plugin so we can do next step.

I see context switcher feature so it is probably because of 3rd party plugin conflict.

If you have that bug without any 3rd party plugin activated i will add bug label

**Comment by AnInfiniteNumberofMonkeys** [comment]
It still occurs when Editor Enhancer is disabled.
<img width="2558" alt="Screen Shot 2021-07-03 at 7 29 47 PM" src="https://user-images.githubusercontent.com/13838253/124371286-1ba35b00-dc35-11eb-89ae-6664675d18f1.png">

**Comment by re-co** [comment]
Hard reload browser (for my firefox dev browser: ctrl + f5)

Plugin is disabled but EE/Hydrogen/some other CSS is cached and i can see that because of structure icons and HOME in topbar which is not from this plugin.

![image](https://user-images.githubusercontent.com/77888923/124378315-f7855f80-dcb0-11eb-94a7-4230329162b5.png)
