### ISSUE TITLE
Mystery button: what does it do?

### ISSUE THREAD

**Issue by AnInfiniteNumberofMonkeys** [re-co/recoda-ws#21]
There's a button labelled "ADD" under the Attribute button...it has a green circle above it. When clicked, this button does nothing except change the circle to orange. Is it broken?
<img width="42" alt="Screen Shot 2021-07-02 at 6 30 11 PM" src="https://user-images.githubusercontent.com/13838253/124369111-32d64e80-dc1d-11eb-9785-55be0f8bbec8.png">

<img width="353" alt="Screen Shot 2021-07-03 at 4 40 19 PM" src="https://user-images.githubusercontent.com/13838253/124369120-5d280c00-dc1d-11eb-9d14-3dce46412b2b.png">

**Comment by re-co** [comment]
Add should show additional options for direct access to wordpress, design sets, helpers etc.

Please disable Editior Enhancer! 
We are not testing plugin with other 3rd party plugins, we need resolve issues between oxygen and this plugin so we can do next step.

Until bug is confirmed in native Oxygen this will be labeled as 3rd party bug and not be on our priority list because we need test plugin with core first

**Comment by AnInfiniteNumberofMonkeys** [comment]
OK, but I'm not going to disable Editor Enhancer, because Oxygen takes almost 30 seconds to show the editor I count on the Context switching feature 100% of the time. I think you'll find there aren't many people who use Oxygen without any 3rd-party plugins to fill in the gaps that the Oxygen developers left. I guess I'll just not use this particular feature until it's fixed.

**Comment by re-co** [comment]
This is testing phase, my plugin in not even 1.0.0 so in this testing we are looking for bugs to bare Oxygen. 
For 3rd party support it should be done after some core issues are solved.
