### ISSUE TITLE
Code editor is very small

### ISSUE THREAD

**Issue by AnInfiniteNumberofMonkeys** [re-co/recoda-ws#23]
All code editing areas are very small when the plugin is active.
<img width="1034" alt="Screen Shot 2021-07-03 at 4 51 56 PM" src="https://user-images.githubusercontent.com/13838253/124369281-fd326500-dc1e-11eb-90f7-e90676c9b0f0.png">

**Comment by re-co** [comment]
Thanks for feedback, 
I know this issue, i need write 2-3 CSS rules to make it full height ( I had it in on production version, but removed becasue it will be attached to claass) So you will have option to turn off/onn enhancments of each panel.

**Comment by re-co** [comment]
Fixed in 0.9.0 and added solution as whole:
![image](https://user-images.githubusercontent.com/77888923/126838566-c5ead24c-7c98-4f24-9291-10cd0dafb4dc.png)
![image](https://user-images.githubusercontent.com/77888923/126838591-deca4165-0619-41bb-85b7-8ec75c4ad260.png)
![image](https://user-images.githubusercontent.com/77888923/126838629-efcb3a07-9a14-4bf6-a68d-8473ad5a3038.png)
+ standardized buttons appereance and small UI tweaks also made
